### ISSUE TITLE
Missing functionality in class_diagram.png

### ISSUE THREAD

**Issue by Abergard** [NadzwyczajnaGrupaRobocza/bomberman#51]
![](https://raw.githubusercontent.com/NadzwyczajnaGrupaRobocza/bomberman/master/docs/img/class_diagram.png)

RenderEngine and PhysicsEngine interfaces doesn't have register/deregister functions.
We should consider to add RenderEngine::register(texture_id, size={1,1}, pos={0,0}) and
PhysicsEngine::register(size={1,1}, pos={0,0})

**Comment by moose-x86** [comment]
Done, closing this issue.
